# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: HunterPie.HunterPie
PackageVersion: 2.12.1.86
PackageLocale: en-US
Publisher: HunterPie
PublisherUrl: https://github.com/HunterPie
PublisherSupportUrl: https://docs.hunterpie.com/
PackageName: HunterPie
PackageUrl: https://github.com/HunterPie/HunterPie
License: MIT
LicenseUrl: https://github.com/HunterPie/HunterPie/blob/HEAD/LICENSE
ShortDescription: A clean, modern and robust overlay for Monster Hunter games.
Description: 'HunterPie v2 is a version of HunterPie completely rewritten from scratch, however, it follows the same principles of its predecessor: being a modern, powerful and easy to use overlay with support for plugins, modules and custom widgets for Monster Hunter: World and Monster Hunter: Rise.'
Moniker: HunterPie
Tags:
- discord
- hunterpie
- hunterpie-v2
- monster-hunter-rise
- monster-hunter-wilds
- monster-hunter-world
- overlay
ReleaseNotes: |-
  What's Changed
  - feat(core): add support to mhwilds v1.30.2.0 by @Haato3o in #708
  Full Changelog: v2.12.1.84...v2.12.1.86
ReleaseNotesUrl: https://github.com/HunterPie/HunterPie/releases/tag/v2.12.1.86
ManifestType: defaultLocale
ManifestVersion: 1.10.0
