# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: yukimemi.shun
PackageVersion: 5.4.3
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: shun
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- ProductCode: shun
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\shun'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yukimemi/shun/releases/download/v5.4.3/shun_5.4.3_x64-setup.exe
  InstallerSha256: 6331F6908273D1E04D6AC4CDDE72838BD20534A8753EC7DD321DF7BBD00042ED
ManifestType: installer
ManifestVersion: 1.12.0
