# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: ServersCom.srvctl
PackageVersion: 1.5.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: srvctl.exe
  PortableCommandAlias: srvctl
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/serverscom/srvctl/releases/download/v1.5.0/srvctl_1.5.0_windows_amd64.zip
  InstallerSha256: 4C859C27868CE6B10F386EB088A899ED453995D0CF977E7D50BECB5B188FEAE5
- Architecture: arm64
  InstallerUrl: https://github.com/serverscom/srvctl/releases/download/v1.5.0/srvctl_1.5.0_windows_arm64.zip
  InstallerSha256: B7F8A062A859B0862A69908A4A642094559CCDC94F8191502B49A723527854C8
ManifestType: installer
ManifestVersion: 1.12.0
