# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: FelipeSantos.VolumeLocker
PackageVersion: 0.8.10
InstallerType: portable
Commands:
- VolumeLocker
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/felipecrs/volume-locker/releases/download/v0.8.10/VolumeLocker.exe
  InstallerSha256: E01EF2D9AE411462516D2D04835A9DF9B9C19D81E6809D8EA6075A6E108F1E8D
ManifestType: installer
ManifestVersion: 1.12.0
