PackageIdentifier: Hinaser.IsImeOn
PackageVersion: 0.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: IsImeOn\IsImeOn.exe
    PortableCommandAlias: IsImeOn
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Hinaser/is-ime-on/releases/download/v0.2.0/IsImeOn-0.2.0-win-x64.zip
    InstallerSha256: 8D759C900385EEB08281518D3F6EF8C93E5ECD340ED58C693C34373A2914158E
ManifestType: installer
ManifestVersion: 1.6.0
