# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.198
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.198/anchors_0.1.198_windows_amd64.zip
  InstallerSha256: D53D4E663C8CF8F70E9D161181C73632E0F64983FBEFB5DF2BA9488E5C55807B
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.198/anchors_0.1.198_windows_arm64.zip
  InstallerSha256: 9B5FEFACFA4E18065AD299ED2C209F06090851AF1525A95E663DA6054EEBE923
ManifestType: installer
ManifestVersion: 1.12.0
